spring:
  profiles:
    active: local

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 간단 출력용 로그레벨 설정 (임시)
logging:
  level:
    root: info
    org:
      springframework:
        jdbc: debug
        web: debug
        boot:
          env: debug
          context: debug